"""Catalogo de extras opcionais do Personal Hub."""

from __future__ import annotations

EXTRAS: dict[str, dict] = {
    "video": {
        "slug": "video",
        "nome": "Video",
        "descricao": "Conversao de videos para MP4, WebM, GIF, MKV ou MOV.",
        "icone": "bi-camera-video",
        "packages": ["imageio-ffmpeg==0.5.1"],
        "imports": ["imageio_ffmpeg"],
        "modulos": ["convert_video"],
        "escopo_dados": "video",
        "persistencia": {
            "tipo": "arquivos",
            "rotulo": "Uploads e videos convertidos",
            "caminho": "storage/uploads/video · storage/outputs/video",
        },
    },
    "imagem": {
        "slug": "imagem",
        "nome": "Imagem",
        "descricao": "Conversao de imagens para WebP, PNG, JPEG, GIF, BMP e TIFF.",
        "icone": "bi-image",
        "packages": ["pillow==11.0.0"],
        "imports": ["PIL"],
        "modulos": ["convert_image"],
        "escopo_dados": "imagem",
        "persistencia": {
            "tipo": "arquivos",
            "rotulo": "Uploads e imagens convertidas",
            "caminho": "storage/uploads/imagem · storage/outputs/imagem",
        },
    },
    "wp-screenshot": {
        "slug": "wp-screenshot",
        "nome": "Screenshot WordPress",
        "descricao": "Padroniza imagens em 1200x900 PNG otimizado (usa Pillow).",
        "icone": "bi-window",
        "packages": ["pillow==11.0.0"],
        "imports": ["PIL"],
        "modulos": ["wp_screenshot"],
        "escopo_dados": "wp-screenshot",
        "persistencia": {
            "tipo": "arquivos",
            "rotulo": "Uploads e PNGs gerados",
            "caminho": "storage/uploads/wp-screenshot · storage/outputs/wp-screenshot",
        },
    },
    "pdf": {
        "slug": "pdf",
        "nome": "Desbloquear PDF",
        "descricao": "Remove senha de PDFs com lista persistente cadastrada.",
        "icone": "bi-file-earmark-lock",
        "packages": ["pikepdf==9.4.2"],
        "imports": ["pikepdf"],
        "modulos": ["unlock_pdf"],
        "escopo_dados": "unlock-pdf",
        "persistencia": {
            "tipo": "arquivos",
            "rotulo": "PDFs + senhas cadastradas no SQLite",
            "caminho": "storage/uploads/unlock-pdf · storage/outputs/unlock-pdf · storage/hub.db",
        },
    },
    "ai": {
        "slug": "ai",
        "nome": "Assistente de IA",
        "descricao": "Chat local com Ollama — modelos focados em programacao e seguranca (DeepHat).",
        "icone": "bi-robot",
        "packages": ["httpx==0.27.2", "pypdf==5.1.0"],
        "imports": ["httpx", "pypdf"],
        "modulos": ["ai_chat"],
        "escopo_dados": "ai-chat",
        "persistencia": {
            "tipo": "sqlite",
            "rotulo": "Conversas e mensagens",
            "caminho": "storage/hub.db",
        },
    },
    "rede": {
        "slug": "rede",
        "nome": "DNS e Whois",
        "descricao": "DNS, Whois, IP/geo, HTTP/TLS, portas, ping, crt.sh, RBL, Shodan, AbuseIPDB e VirusTotal.",
        "icone": "bi-globe2",
        "packages": ["dnspython==2.7.0", "python-whois==0.9.4", "httpx==0.27.2"],
        "imports": ["dns", "whois", "httpx"],
        "modulos": ["rede_lookup"],
        "escopo_dados": "rede-lookup",
        "persistencia": {
            "tipo": "config",
            "rotulo": "So chaves de API (Shodan, AbuseIPDB, VirusTotal)",
            "caminho": "storage/hub.db (settings)",
        },
    },
    "crypto": {
        "slug": "crypto",
        "nome": "Criptografar / Descriptografar",
        "descricao": "AES-256-GCM no navegador (PBKDF2). Compativel com gcm-encrypt-decrypt.",
        "icone": "bi-shield-lock",
        "packages": [],
        "imports": [],
        "modulos": ["gcm_crypto"],
        "escopo_dados": "gcm-crypto",
        "persistencia": {
            "tipo": "nenhum",
            "rotulo": "Nada gravado em disco",
            "caminho": "—",
        },
    },
    "cofre": {
        "slug": "cofre",
        "nome": "Cofre de senhas",
        "descricao": "Arquivo .hubvault criptografado (AES-GCM). Senha-mestra so no navegador.",
        "icone": "bi-safe2",
        "packages": [],
        "imports": [],
        "modulos": ["cofre_senhas"],
        "escopo_dados": "cofre-senhas",
        "persistencia": {
            "tipo": "vault",
            "rotulo": "Cofres criptografados (.hubvault)",
            "caminho": "storage/vaults/*.hubvault",
        },
    },
    "fake": {
        "slug": "fake",
        "nome": "Dados fake",
        "descricao": "Gera perfis (nome, e-mail, CPF...) editaveis e salva em .hubfake criptografado.",
        "icone": "bi-person-vcard",
        "packages": [],
        "imports": [],
        "modulos": ["fake_data"],
        "escopo_dados": "fake-data",
        "persistencia": {
            "tipo": "vault",
            "rotulo": "Colecoes de perfis (.hubfake)",
            "caminho": "storage/fake-profiles/*.hubfake",
        },
    },
    "totp": {
        "slug": "totp",
        "nome": "Authenticator 2FA",
        "descricao": "Codigos TOTP locais. Backup .hubtotp criptografado pra pendrive.",
        "icone": "bi-phone",
        "packages": [],
        "imports": [],
        "modulos": ["totp_auth"],
        "escopo_dados": "totp-auth",
        "persistencia": {
            "tipo": "vault",
            "rotulo": "Vaults TOTP (.hubtotp)",
            "caminho": "storage/totp-vaults/*.hubtotp",
        },
    },
    "lan-dm": {
        "slug": "lan-dm",
        "nome": "Chat (LAN)",
        "descricao": "Chat em tempo real na rede local — texto e arquivos entre PCs conectados ao hub.",
        "icone": "bi-chat-dots",
        "packages": [],
        "imports": [],
        "modulos": ["lan_dm"],
        "somente_lan": True,
        "escopo_dados": "lan-dm",
        "persistencia": {
            "tipo": "sqlite",
            "rotulo": "Mensagens e anexos na LAN",
            "caminho": "storage/hub.db · storage/lan-dm/arquivos",
        },
    },
}


def eh_browser_only(extra: dict) -> bool:
    """Extra sem pip nem imports Python — ativacao so pela Loja."""
    return not extra.get("packages") and not extra.get("imports")


# Formatos das categorias (slug da tool -> chave do modulo)
FORMATOS_VIDEO = [
    {"slug": "convert-mp4", "label": "MP4 (H.264)", "formato": "mp4", "padrao": True},
    {"slug": "convert-webm", "label": "WebM (VP9)", "formato": "webm", "padrao": False},
    {"slug": "convert-gif", "label": "GIF animado", "formato": "gif", "padrao": False},
    {"slug": "convert-mkv", "label": "MKV (H.264)", "formato": "mkv", "padrao": False},
    {"slug": "convert-mov", "label": "MOV (H.264)", "formato": "mov", "padrao": False},
]

FORMATOS_IMAGEM = [
    {"slug": "convert-webp", "label": "WebP", "formato": "webp", "padrao": True},
    {"slug": "convert-png", "label": "PNG", "formato": "png", "padrao": False},
    {"slug": "convert-jpeg", "label": "JPEG", "formato": "jpeg", "padrao": False},
    {"slug": "convert-gif-img", "label": "GIF", "formato": "gif", "padrao": False},
    {"slug": "convert-bmp", "label": "BMP", "formato": "bmp", "padrao": False},
    {"slug": "convert-tiff", "label": "TIFF", "formato": "tiff", "padrao": False},
]

TOOL_META: dict[str, dict] = {
    "wp_screenshot": {
        "slug": "wp-screenshot",
        "nome": "Screenshot WordPress",
        "descricao": "Padroniza imagens em 1200x900 PNG otimizado.",
        "icone": "bi-window",
        "aceita": "image/*",
        "controles": "wp-screenshot",
        "extra": "wp-screenshot",
    },
    "unlock_pdf": {
        "slug": "unlock-pdf",
        "nome": "Desbloquear PDF",
        "descricao": "Remove senha de PDFs usando lista persistente cadastrada.",
        "icone": "bi-file-earmark-lock",
        "aceita": ".pdf,application/pdf",
        "controles": "unlock",
        "extra": "pdf",
    },
    "ai_chat": {
        "slug": "ai-chat",
        "nome": "Assistente de IA Local",
        "descricao": "Chat local com Ollama — modelos focados em programacao e seguranca (DeepHat).",
        "icone": "bi-robot",
        "aceita": "",
        "controles": "ai",
        "extra": "ai",
    },
    "rede_lookup": {
        "slug": "rede-lookup",
        "nome": "DNS e Whois",
        "descricao": "Lookup completo de rede: DNS, Whois, TLS, portas, reputacao e Shodan.",
        "icone": "bi-globe2",
        "aceita": "",
        "controles": "rede",
        "extra": "rede",
    },
    "gcm_crypto": {
        "slug": "gcm-crypto",
        "nome": "Criptografar / Descriptografar",
        "descricao": "AES-256-GCM no navegador — nada sobe pro servidor.",
        "icone": "bi-shield-lock",
        "aceita": "",
        "controles": "crypto",
        "extra": "crypto",
    },
    "cofre_senhas": {
        "slug": "cofre-senhas",
        "nome": "Cofre de senhas",
        "descricao": "Cofre local criptografado — importar, exportar e excluir.",
        "icone": "bi-safe2",
        "aceita": "",
        "controles": "cofre",
        "extra": "cofre",
    },
    "fake_data": {
        "slug": "fake-data",
        "nome": "Dados fake",
        "descricao": "Gera e edita perfis falsos — backup criptografado .hubfake.",
        "icone": "bi-person-vcard",
        "aceita": "",
        "controles": "fake",
        "extra": "fake",
    },
    "totp_auth": {
        "slug": "totp-auth",
        "nome": "Authenticator 2FA",
        "descricao": "Codigos TOTP no navegador — backup .hubtotp criptografado.",
        "icone": "bi-phone",
        "aceita": "",
        "controles": "totp",
        "extra": "totp",
    },
    "lan_dm": {
        "slug": "lan-dm",
        "nome": "Chat (LAN)",
        "descricao": "Chat na rede local — texto e arquivos entre PCs, em tempo real.",
        "icone": "bi-chat-dots",
        "aceita": "",
        "controles": "lan-dm",
        "extra": "lan-dm",
    },
}
